services:
  - type: web
    name: gramma-backend
    env: python
    plan: free
    region: oregon
    buildCommand: |
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
    autoDeploy: true
    buildFilter:
      paths:
        - backend/**
    repo: https://github.com/Ommooley10/GrammaScan
    rootDir: backend

  - type: web
    name: gramma-frontend
    env: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm run start
    staticPublishPath: out
    autoDeploy: true
    buildFilter:
      paths:
        - frontend/**
    repo: https://github.com/Ommooley10/GrammaScan
    rootDir: frontend
